project/api/urls.py
from django.urls import path, re_path, include, reverse_lazy
from . import views


urlpatterns = [
    path('', views.api_index, name='api_index'),
    path('all/', views.api_all_tasks, name='api_all_tasks'),
    path('new/', views.api_new_task, name='api_new_task'),
    path('update/', views.api_update_task, name='api_update_task'),
    path('delete/', views.api_delete_task, name='api_delete_task'),
    path('signin/', views.api_signin, name='api_signin'),
]

project/internship/urls.py
from django.urls import path, re_path, include, reverse_lazy
from . import views


urlpatterns = [
    path('companies/', views.companies_page, name='companies'),
    path('courses/', views.courses_page, name='courses'),
    path('students/', views.students_page, name='students'),
    path('events/', views.events_page, name='events'),
    path('vacancy/<int:vacancy_id>', views.vacancy_detail_page, name='vacancy_detail'),
    path('companies/<int:company_id>', views.company_detail_page, name='company_detail'),
    path('', views.vacancy_page, name='vacancy'),
]

project/project/urls.py
import os

from django.conf import settings
from django.contrib import admin
from django.http import HttpResponse
from django.urls import path, include, re_path, reverse_lazy
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

import internship.views
from project.views import index_page

admin.site.site_header = 'StudWorks админ. панель'
admin.site.index_title = 'Управление разделами сайта'
admin.site.site_title = 'StudWorks админ. панель'


def update_university(request):
    from site_settings.models import University
    from site_settings.utils.univeristy_info import university_json
    for item in university_json:
        University.objects.update_or_create(
            name=item['name'],
            defaults={'name': item['name']}
        )
    return HttpResponse('ok')


urlpatterns = [
    path('profile/', include(('user_profile.urls', 'profile'), namespace='profile')),
    path('internship/', include(('internship.urls', 'internship'), namespace='internship')),
    path('api/', include(('api.urls', 'api'), namespace='api')),

    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(
        template_name='user_profile/password_reset_done.html'
    ), name='password_reset_done'),
    re_path(r'password_reset_confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            auth_views.PasswordResetConfirmView.as_view(
                template_name='user_profile/password_reset_confirm.html'
            ), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='user_profile/password_reset_complete.html'
    ), name="password_reset_complete"),
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name="user_profile/password_reset.html",
        html_email_template_name="email_templates/password_reset_email.html",
        success_url=reverse_lazy('password_reset_done'),
    ), name='password_reset'),

    path('admin/', admin.site.urls),
    path('update_university/', update_university),
    path('', index_page, name='index'),

]

if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        path('favicon.ico', RedirectView.as_view(url=settings.STATIC_URL + 'content/images/favicon.ico'))
    ]
else:
    import django.views.static

    urlpatterns += [
        re_path(r'^static/(?P<path>.*)$', django.views.static.serve,
                {'document_root': settings.STATIC_ROOT, 'show_indexes': settings.DEBUG})
    ]

project/user_profile/urls.py
from django.urls import path, re_path, include, reverse_lazy
from . import views


urlpatterns = [
    # path('<username>/', views.category_page, name='category'),
    path('logout/', views.logout_view, name='logout'),
    path('login/', views.login_view, name='login'),
    path('registration/', views.registration_view, name='registration'),
    path('edit/', views.edit_profile_view, name='edit'),


    # path('', include('django.contrib.auth.urls')),
    path('', views.profile_view, name='profile'),
]

project/site_settings/models.py
from django.contrib.auth.models import User
from django.db import models


class University(models.Model):
    name = models.CharField('Наименование учебного заведения', max_length=200)

    class Meta:
        verbose_name = "университет"
        verbose_name_plural = "Университеты"


class Companies(models.Model):
    avatar = models.ImageField('Аватар компании', upload_to='companies/', blank=True, null=True)
    small_descripton = models.CharField('Краткое описание компании', max_length=120, blank=True, null=True)
    url = models.URLField('Ссылка на организацию', blank=True, null=True)
    bin = models.CharField('БИН', primary_key=True, max_length=12, editable=False)
    address = models.CharField('Адрес организации', max_length=500)
    name = models.CharField('Наименование ', max_length=200)


    class Meta:
        verbose_name = "компания"
        verbose_name_plural = "Компании"


class Events(models.Model):
    image = models.ImageField('Изображение события', upload_to='companies/', blank=True, null=True)
    small_descripton = models.CharField('Краткое описание события', max_length=120, blank=True, null=True)
    url = models.URLField('Ссылка', blank=True, null=True)
    organizer = models.ForeignKey(Companies, on_delete=models.SET_NULL, null=True)

    class Meta:
        verbose_name = "компания"
        verbose_name_plural = "Компании"

project/site_settings/views.py
from django.shortcuts import render

# Create your views here.

project/site_settings/templates/site_settings/base.html
<!DOCTYPE html>
<html lang="ru">

{% load static %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>{% block title %}{% endblock %} StudWorks - сервис по поиску практики</title>

    <link href="https://fonts.googleapis.com/css?family=Oswald:400,500,600,700%7CPoppins:400,400i,500,600&display=swap" rel="stylesheet">


    <link href="{% static 'site_settings/css/slicknav.min.css' %}" rel="stylesheet" />
    <link href="{% static 'site_settings/css/font-awesome.css' %}" rel="stylesheet" />
    <link href="{% static 'site_settings/css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'site_settings/css/style.css' %}" rel="stylesheet" />

    {% block extra_head %}
    {# Для вставки head на отдельно со страницы #}
    {% endblock %}
</head>


<body>

 <header class="header-area">

        <div class="header-top">
            <div class="container  ">
                <nav class="navbar-expand-lg navbar-dark">
                    <div class="d-flex bd-highlight">
                        <div class="nav-item mr-auto p-2 bd-highlight">
                            <div class="site-logo">
                                <a href="/" class="logo"><span class="stud-span">Stud</span><span class="works-span">Works</span> </a>
                            </div>
                        </div>
                        <div class="nav-item p-2 bd-highlight">
                            <a class="nav-link" href="info_page.html">Помощь</a>
                        </div>
                        <div class="nav-item p-2 bd-highlight">
                            <a class="nav-link" href="info_page.html">Работодателям</a>
                        </div>
                        <div class="nav-item  p-2 bd-highlight">
                            <a class="nav-link" href="info_page.html">Студентам</a>
                        </div>
                      <div class="nav-item  p-2 bd-highlight">
                            <a class="nav-link" href="{% url 'api:api_index' %}">Разработчикам</a>
                        </div>
                      </div>
                </nav>

            </div>
        </div>
        <div class="header-middle">
            <div class="container  ">
                <nav class="navbar navbar-expand-lg px-0 navbar-light">
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                      <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                          <a class="nav-link" href="{% url 'internship:vacancy' %}">Вакансии</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'internship:companies' %}">Компании</a>
                          </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'internship:courses' %}">Курсы</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'internship:students' %}">Студенты</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'internship:events' %}">События</a>
                        </li>
                      </ul>
                      <form class="form-inline">
                          {% if request.user.is_authenticated %}
                            <a class="btn reg-btn text-white" href="{% url 'profile:logout' %}">Выйти</a>
                          {% else %}
                            <a class="btn log-btn" href="{% url 'profile:login' %}">Войти</a>
                            <a class="btn reg-btn text-white" href="{% url 'profile:registration' %}">Регистрация</a>
                          {% endif %}
                      </form>
                    </div>
                </nav>
            </div>
        </div>
    </header>
<main>
    {% block content %}{% endblock %}
</main>
<!--== Start Footer Area Wrapper ==-->
    <footer class="footer-area">
        <div class="footer-widget-area">
            <div class="container  ">
                <div class="row mtn-40">
                    <div class="col-lg-6">
                        <div class="widget-item">

                            <div class="about-widget">
                                <div class="site-logo mb-2 mtop-minus-1">
                                    <a href="index.html" class="logo mb-3"><span class="stud-span">Stud</span><span class="works-span">Works</span> </a>
                                </div>
                                <p>Мечтаете о головокружительной карьере? Начинать никогда не рано! Стажировка для студентов или производственная практика — отличный старт. И хотя скептики говорят, что без опыта нет работы, а без работы нет опыта, мы знаем, как разорвать этот порочный круг. Вы научитесь видеть свои профессиональные возможности, планировать карьеру, а по окончании вуза найдете лучшую для себя работу по специальности.Не ждите получения диплома — начинайте прямо сейчаc!</p>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-6 col-lg-2">
                        <div class="widget-item">
                            <h4 class="widget-title">Страницы</h4>
                            <div class="widget-body">
                                <ul class="widget-list">
                                    <li>
                                        <a href="{% url 'internship:vacancy' %}">Вакансии</span></a>
                                      </li>
                                      <li>
                                          <a href="{% url 'internship:companies' %}">Компании</a>
                                        </li>
                                      <li>
                                        <a href="{% url 'internship:courses' %}">Курсы</a>
                                      </li>
                                      <li>
                                        <a href="{% url 'internship:students' %}">Студенты</a>
                                      </li>
                                      <li>
                                          <a href="{% url 'internship:events' %}">События</a>
                                      </li>
                                </ul>
                            </div>
                        </div>
                    </div>



                    <div class="col-sm-6 col-lg-3">
                        <div class="widget-item">
                            <h4 class="widget-title">Помощь</h4>
                            <div class="widget-body">
                                <ul class="widget-list">
                                    <li>
                                        <a href="#">Ссылка</span></a>
                                    </li>
                                    <li>
                                        <a href="#">Ccылка</a>
                                    </li>
                                </ul>
                                <address>
                                    2020 Алматы, Казахстан <br>
                                https://Studworks.kz <br>
                                8 (800) 555 35 35                            </address>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="footer-copyright-area">
            <div class="container">
                <div class="row">
                    <div class="col-12 text-center">
                        <div class="copyright-content">
                            <p>Copyright © 2019 StudWorks. All Rights Reserved.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
<!--== End Footer Area Wrapper ==-->

<!-- Scroll Top Button -->

    <script src="{% static 'site_settings/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'site_settings/js/jquery-migrate-1.2.1.min.js' %}"></script>
    <script src="{% static 'site_settings/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'site_settings/js/jquery.slicknav.min.js' %}"></script>
    <script src="{% static 'site_settings/js/slick.min.js' %}"></script>
    <script src="{% static 'site_settings/js/popper.min.js' %}"></script>
    <script src="{% static 'site_settings/js/active.js' %}"></script>

</body>
</html>